# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        ATS\Bundle\MovieBundle\Entity\User:
            algorithm: bcrypt
    
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mysql_provider:
            entity:
                class:    ATSMovieBundle:User
                property: username
    

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: mysql_provider
            
            anonymous: ~
            
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path:          login
                check_path:          login_check
                default_target_path: /
            
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: ROLE_USER }
