<?php

namespace ATS\Bundle\MovieBundle\Repository;

/**
 * MeowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeowRepository extends \Doctrine\ORM\EntityRepository
{
}
