home:
    type:     annotation
    resource: "@ATSMovieBundle/Controller/DefaultController.php"

security:
    type:     annotation
    resource: "@ATSMovieBundle/Controller/SecurityController.php"

api:
    type:     rest
    resource: "@ATSMovieBundle/Controller/MovieController.php"
